name: Windows - Pre Release(latest)
on:
  push:
    branches:
      - "master"
jobs:
  windows-prerelease:
    name: Windows - Pre Release(latest)
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - name: Download source
        uses: actions/checkout@v2
      - name: Install Crystal
        run: |
          Set-ExecutionPolicy RemoteSigned -Scope CurrentUser
          irm get.scoop.sh -outfile 'install.ps1'
          .\install.ps1 -RunAsAdmin
          echo ("PATH=" + $env:PATH + ";" + $home + "\scoop\shims") >> $env:GITHUB_ENV
          scoop bucket add crystal-preview https://github.com/neatorobito/scoop-crystal
          scoop install vs_2022_cpp_build_tools
          scoop install crystal
      - name: shards install
        run: shards install
      - name: Setup VS Dev Environment
        uses: seanmiddleditch/gha-setup-vsdevenv@v4
      - name: raylib-cr post-install
        run: |
          powershell lib/raylib-cr/rsrc/install-lib.ps1
          echo ("LIB=" + $env:LIB + ";" + $pwd + "\libs") >> $env:GITHUB_ENV
          echo ("PATH=" + $env:PATH + ";" + $pwd + "\libs") >> $env:GITHUB_ENV
      - name: Build map-viewer
        run: |
          shards build --release map-viewer
          Remove-Item "bin\*.pdb" -Recurse -Force
      - name: Zip
        run: Compress-Archive -Path "bin/*" -DestinationPath windows-map-viewer.zip
      - uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          tag: "latest"
          prerelease: true
          artifacts: "windows-map-viewer.zip"
      - name: Cleanup
        run: Remove-Item -Path "bin" -Recurse -Force
      - name: Build wad-viewer
        run: |
          shards build --release wad-viewer
          Remove-Item "bin\*.pdb" -Recurse -Force
      - name: Zip
        run: Compress-Archive -Path "bin/*" -DestinationPath windows-wad-viewer.zip
      - uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          tag: "latest"
          prerelease: true
          artifacts: "windows-wad-viewer.zip"